// <auto-generated />
using System;
using MedicalModel;
using MedicalService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asm2.Migrations.MedicalProject
{
    [DbContext(typeof(MedicalDbContext))]
    [Migration("20250710075922_addOwnedTypeDoctorInfoToPerson")]
    partial class addOwnedTypeDoctorInfoToPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicalModel.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalModel.Diagnosis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppointmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("MedicalModel.Hospital", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("MedicalModel.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HospitalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MedicalModel.Appointment", b =>
                {
                    b.HasOne("MedicalModel.Person", null)
                        .WithMany("Appointments")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("MedicalModel.Diagnosis", b =>
                {
                    b.HasOne("MedicalModel.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MedicalModel.Person", b =>
                {
                    b.HasOne("MedicalModel.Hospital", null)
                        .WithMany("Doctor")
                        .HasForeignKey("HospitalId");

                    b.OwnsOne("MedicalModel.DoctorInfo", "DoctorInfo", b1 =>
                        {
                            b1.Property<string>("PersonId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("HospitalId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("ProfileImageUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.HasKey("PersonId");

                            b1.HasIndex("HospitalId");

                            b1.ToTable("Persons");

                            b1.HasOne("MedicalModel.Hospital", "Hospital")
                                .WithMany()
                                .HasForeignKey("HospitalId");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.Navigation("Hospital");
                        });

                    b.Navigation("DoctorInfo");
                });

            modelBuilder.Entity("MedicalModel.Hospital", b =>
                {
                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalModel.Person", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
